# This file was made with the assistance of AI tools!
name: Unit Tests

on:
  push:
    branches:
      - feature #Trigger on feature branch

jobs:
  unit-testing:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0'

      - name: Restore dependencies
        run: dotnet restore

      - name: Setup build configuration
        run: |
          cat <<EOF > Directory.Build.props
          <Project>
              <PropertyGroup>
                  <OutputPath>\$(SolutionDir)Output\</OutputPath>
              </PropertyGroup>
          </Project>
          EOF

      - name: Build Core
        run: dotnet build ./PhysiXSharp.Core/PhysiXSharp.Core.csproj --configuration Release

      - name: Build solution
        run: dotnet build --no-restore

      - name: Run all tests
        run: dotnet test --no-build --verbosity normal