# This file was made with the assistance of AI tools!
name: Unit Tests

on:
  push:
    branches:
      - feature #Trigger on feature branch

jobs:
  unit-testing:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Checkout DLLs repository
        uses: actions/checkout@v2
        with:
          repository: VinciDa33/motus-sfml-dlls
          path: dlls 

      - name: Create NativeLibs directory
        run: mkdir -p ./MotusPhysics.Visualizer/NativeLibs

      - name: Copy C++ native DLLs to the project
        run: |
          cp -r dlls/native-libs/* ./MotusPhysics.Visualizer/NativeLibs/

      - name: Copy C# wrappers to the project
        run: |
          cp -r dlls/wrappers/* ./MotusPhysics.Visualizer/Resources/


      - name: Set up .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0'

      - name: Restore dependencies
        run: dotnet restore
          
      - name: Build solution
        run: dotnet build --no-restore

      - name: Run all tests
        run: dotnet test --no-build --verbosity normal